#!/usr/bin/env bash

# Initialize
printf "$$" > ~/.cache/pidofbar
sec=0

# Update functions
update_time() {
  time=$(date "+%b %d %H:%M ")
}

update_bat() {
  if [[ -e /sys/class/power_supply/BAT1/capacity ]]; then
    bat_capacity=$(< /sys/class/power_supply/BAT1/capacity)
    if (( bat_capacity == 100 )); then
      bat="󰁹 $bat_capacity%"
    elif (( bat_capacity >= 90 )); then
      bat="󰂂 $bat_capacity%"
    elif (( bat_capacity >= 80 )); then
      bat="󰂁 $bat_capacity%"
    elif (( bat_capacity >= 70 )); then
      bat="󰂀 $bat_capacity%"
    elif (( bat_capacity >= 60 )); then
      bat="󰁿 $bat_capacity%"
    elif (( bat_capacity >= 50 )); then
      bat="󰁾 $bat_capacity%"
    elif (( bat_capacity >= 40 )); then
      bat="󰁽 $bat_capacity%"
    elif (( bat_capacity >= 30 )); then
      bat="󰁼 $bat_capacity%"
    elif (( bat_capacity >= 20 )); then
      bat="󰁻 $bat_capacity%"
    elif (( bat_capacity >= 10 )); then
      bat="󰁺 $bat_capacity%"
    else
      bat="󰂄 $bat_capacity%"
    fi
  else
    bat="(capacity not available)"
  fi
}

update_vol() {
  vol="奄 $(pactl list sinks | awk '/Volume:/ {print $5}' | head -n 1 | tr -d '%')%"
}

update_wifi() {
  if ping -c 1 ping.archlinux.org &> /dev/null; then
    wifi="󰛳"
  else
    wifi="󰅛"
  fi
}

update_backlight() {
  if [[ -e /sys/class/backlight/intel_backlight/actual_brightness ]]; then
    actual_brightness=$(< /sys/class/backlight/intel_backlight/actual_brightness)
    max_brightness=$(< /sys/class/backlight/intel_backlight/max_brightness)
    backlight="☀$((actual_brightness * 100 / max_brightness))%"
  fi
}

# Display function
display() {
  status=""
  [[ -n "$bat" ]] && status+="$bat │"
  [[ -n "$backlight" ]] && status+="$backlight │"
  [[ -n "$vol" ]] && status+="$vol │"
  [[ -n "$wifi" ]] && status+="$wifi │"
  [[ -n "$time" ]] && status+="$time"
  xsetroot -name "$status"
}

# Set up signal handlers
trap "update_vol; display" "RTMIN"
trap "update_backlight; display" "RTMIN+1"
trap "update_bat; display" "RTMIN+2"

# Initial updates
update_vol
update_backlight

# Main loop
while true; do
  sleep 1
  sec=$((sec + 1))
  case $((sec % 60)) in
    0) update_bat;;
    [1-5]) 
      update_time
      update_vol
      update_wifi
      display
      ;;
  esac
done

