#!/bin/bash

# Initialize
printf "$$" > ~/.cache/pidofbar
sec=0

# Update functions
update_time() {
  time=$(date "+%b %d %H:%M ")
}

update_bat() {
  if [[ -e /sys/class/power_supply/BAT1/capacity ]]; then
    bat_capacity=$(< /sys/class/power_supply/BAT1/capacity)
    bat="⚡ $bat_capacity%"
  else
    bat="(capacity not available)"
  fi
}

update_vol() {
  vol="🎶 $(pactl list sinks | awk '/Volume:/ {print $5}' | head -n 1 | tr -d '%')%"
}

# Display function
display() {
  status=""
  [[ -n "$vol" ]] && status+=" $vol │"
  [[ -n "$bat" ]] && status+=" $bat │"
  [[ -n "$time" ]] && status+=" $time"
  xsetroot -name "$status"
}

# Set up signal handlers
trap "update_bat; display" "RTMIN+2"
trap "update_vol; display" "RTMIN"

# Initial updates
update_vol

# Main loop
while true; do
  sleep 1
  sec=$((sec + 1))
  case $((sec % 60)) in
    0) update_bat;;
    [1-5]) 
      update_time
      update_vol
      display
      ;;
  esac
done

